name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
    paths-ignore:
      - '**/README.md'
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ncecere/vllm

jobs:
  cpu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
            suffix=-cpu
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ env.IMAGE_NAME }}
      - name: Build and push AMD64 Docker image to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.cpu
          push: ${{ github.event_name == 'push' }}
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/vllm:cpu-latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  cuda-arm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
            suffix=-cuda-arm
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ env.IMAGE_NAME }}
      - name: Build and push ARM64 CUDA Docker image to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.cuda-arm
          push: ${{ github.event_name == 'push' }}
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/vllm:cuda-arm-latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
